# Generated by Django 5.0.6 on 2024-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('special', 'Специальные'), ('other', 'Иные'), ('public', 'Общедоступные'), ('biometric', 'Биометрия')], max_length=50)),
                ('number_of_people', models.CharField(choices=[('less_100k', 'Меньше 100 тыс.'), ('more_100k', 'Больше 100 тыс.')], max_length=50)),
                ('threat_type', models.CharField(choices=[('1', 'Тип 1'), ('2', 'Тип 2'), ('3', 'Тип 3')], max_length=50)),
                ('security_level', models.CharField(max_length=50)),
            ],
        ),
    ]
